# Generated by Django 4.1.4 on 2023-07-16 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Composant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=100)),
                ('Prix_achat', models.FloatField()),
                ('Prix_vente', models.FloatField()),
                ('quantite', models.FloatField()),
                ('seuil', models.FloatField()),
                ('Langeur', models.FloatField(blank=True)),
                ('Largeur', models.FloatField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=200)),
                ('Prix_achat', models.FloatField()),
                ('Prix_vente', models.FloatField()),
                ('quantite', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=100)),
                ('Prix_achat', models.FloatField()),
                ('Prix_vente', models.FloatField()),
                ('type', models.CharField(max_length=30)),
                ('quantite', models.FloatField()),
                ('seuil', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=100)),
                ('PssWord', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Element_cuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantite', models.FloatField()),
                ('Cuisin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuisineApp.cuisine')),
                ('Element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuisineApp.element')),
            ],
        ),
        migrations.CreateModel(
            name='Composant_Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantite', models.FloatField()),
                ('Cuisin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuisineApp.composant')),
                ('Element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuisineApp.element')),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom_Client', models.CharField(max_length=100)),
                ('prenom_Client', models.CharField(max_length=100)),
                ('Num_tele', models.CharField(max_length=20)),
                ('Mode_paiment', models.CharField(max_length=20)),
                ('Prix_commande', models.FloatField()),
                ('reste_paiment', models.FloatField()),
                ('Date_comm', models.DateField()),
                ('Cuisine', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='cuisineApp.cuisine')),
            ],
        ),
    ]
