# Generated by Django 4.1.4 on 2023-07-16 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuisineApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composant',
            name='Langeur',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='composant',
            name='Largeur',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
