# Generated by Django 4.1.4 on 2023-07-19 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuisineApp', '0002_alter_composant_langeur_alter_composant_largeur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='composant',
            name='Prix_vente',
        ),
    ]
