# Generated by Django 4.1.4 on 2023-07-21 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuisineApp', '0003_remove_composant_prix_vente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='reste_paiment',
            new_name='Prix_Paye',
        ),
    ]
