# Generated by Django 4.1.4 on 2023-07-21 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuisineApp', '0004_rename_reste_paiment_commande_prix_paye'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='Mode_paiment',
            field=models.CharField(choices=[('par tranche', 'par tranche'), ('cash', 'cash')], max_length=20),
        ),
    ]
