# Generated by Django 4.1.4 on 2023-07-21 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuisineApp', '0005_alter_commande_mode_paiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='Prix_Transport',
            field=models.FloatField(default=0),
        ),
    ]
