# Generated by Django 4.1.4 on 2023-07-21 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuisineApp', '0006_commande_prix_transport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuisine',
            name='quantite',
            field=models.FloatField(default=0),
        ),
    ]
