# Generated by Django 4.1.4 on 2023-07-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuisineApp', '0007_alter_cuisine_quantite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuisine',
            name='Prix_achat',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='cuisine',
            name='Prix_vente',
            field=models.FloatField(default=0),
        ),
    ]
