# Generated by Django 4.1.4 on 2023-07-25 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuisineApp', '0008_alter_cuisine_prix_achat_alter_cuisine_prix_vente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='composant_element',
            old_name='Cuisin',
            new_name='composant',
        ),
    ]
