# Generated by Django 4.1.4 on 2023-07-25 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuisineApp', '0009_rename_cuisin_composant_element_composant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='Prix_achat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='Prix_vente',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
