# Generated by Django 4.1.4 on 2023-08-02 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuisineApp', '0010_alter_element_prix_achat_alter_element_prix_vente'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='deliver',
            field=models.BooleanField(default=False),
        ),
    ]
