# Generated by Django 4.1.4 on 2023-08-02 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuisineApp', '0011_commande_deliver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='Num_tele',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='commande',
            name='Prix_commande',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='commande',
            name='deliver',
            field=models.BooleanField(choices=[('livrer', True), ('ne pas livrer', False)], default=False),
        ),
    ]
