# Generated by Django 4.1.4 on 2023-08-02 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuisineApp', '0012_alter_commande_num_tele_alter_commande_prix_commande_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='Prix_Paye',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='commande',
            name='deliver',
            field=models.BooleanField(choices=[(True, 'livrer'), (False, 'ne pas livrer')], default=False),
        ),
    ]
