# Generated by Django 4.1.4 on 2023-08-02 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuisineApp', '0013_alter_commande_prix_paye_alter_commande_deliver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='Cuisine',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='cuisineApp.cuisine'),
        ),
    ]
