# Generated by Django 4.1.4 on 2023-08-02 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuisineApp', '0014_alter_commande_cuisine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='deliver',
            field=models.BooleanField(choices=[(True, 'livrer'), (False, "ñ'est pas livrer")], default=False),
        ),
        migrations.AlterField(
            model_name='element',
            name='quantite',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='element',
            name='seuil',
            field=models.FloatField(default=0),
        ),
    ]
